version: "3.9"

services:
  grussinator-backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - OPENAI_API_KEY=REPLACE_WITH_API_KEY
      - GROQ_API_KEY=REPLACE_WITH_API_KEY
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

